###
### Retrieve a token that can be used for calls requiring authentication
###
POST {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    client.global.set("token", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsInR5cGUiOiJhZG1pbiIsImlhdCI6MTY5ODY3NjI5NCwiZXhwIjoxNjk4Njc5ODk0fQ.-g8SBg_TeGCfPwBG2m8Kis2zOvXRWZSqVXzO9pevc9A");
    client.test(
        "Status code is 200",
        function () {
            client.assert(response.status === 200, "Response status is not 200");
        }
    );
    client.test(
        "Response body is a token",
        function () {
            client.assert(response.body.token !== undefined, "Response body is not a token");
        }
    );
%}
