###
### Retrieve a token that can be used for calls requiring authentication
###
POST {{protocol}}{{host}}:{{port}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    client.test(
        "Status code is 200",
        function () {
            client.assert(response.status === 200, "Response status is not 200");
        }
    );
    client.test(
        "Response body is a token",
        function () {
            client.assert(response.body.token !== undefined, "Response body is not a token");
        }
    );
%}


###
### Register a new user
###

POST {{protocol}}{{host}}:{{port}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "test"
}

> {%
    client.test(
        "Status code is 201",
        function () {
            client.assert(response.status === 201, "Response status is not 201");
        }
    );
%}
